---
title: "Event valence"
subtitle: "Posterior distributions of model parameters"
author: "Szymon Talaga"
date: last-modified
date-format: "MMMM D, YYYY | HH:mm:ss (Z)"
toc: true
toc-depth: 3
toc-location: left
execute:
  echo: false
  warning: false
  cache: false
  daemon: false
format:
  html:
    grid:
      margin-width: 350px
    embed-resources: true
  pdf:
    toc: false
    number-sections: true
    colorlinks: true
reference-location: margin
citation-location: margin
---

```{r}
library(reticulate)
library(stringr)
library(arrow)
library(dplyr)
library(tibble)
library(brms)
library(ggplot2)

theme_set(theme_bw())

use_python(normalizePath(R.home("../../bin/python")), required = TRUE)

project <- import("project")
config  <- project$config
paths   <- project$paths

here     <- paths$analyses / "glmm" / "valence"
glmmpath <- paths$glmm / "valence"
figures  <- paths$root / "figures" / "glmm" / "valence"
figures$mkdir(parents = TRUE, exist_ok = TRUE)

countries <- config$countries$order
countries <- countries[0L:length(countries)]

target <- "event"
model  <- "meanfield"
```

```{r}
glmm <- readRDS(
    as.character(glmmpath / str_glue("{target}-{model}.rds"))
)
```

```{r}
fe_posterior_plot <- plot(
    glmm,
    variable = "^b_", regex = TRUE,
    nvariables = nrow(fixef(glmm)),
)
```

```{r}
ggsave(

)
```
