stages:

  posts:
    cmd: python stages/make_posts.py
    params:
    - posts
    deps:
    - stages/make_posts.py
    - data/raw/posts/
    outs:
    - data/proc/posts.parquet:
        persist: true
    - data/proc/posts-text.parquet:
        persist: true

  daily-counts:
    cmd: python stages/make_daily.py
    deps:
    - stages/make_daily.py
    - data/proc/posts.parquet
    params:
    - dataset.min_posts_per_day
    outs:
    - data/proc/daily.parquet:
        persist: true

  dataset:
    cmd: python stages/make_dataset.py
    deps:
    - stages/make_dataset.py
    - data/proc/posts.parquet
    - data/proc/daily.parquet
    params:
    - dataset.min_posts_per_day
    - dataset.max_decile_difference
    outs:
    - data/proc/dataset.parquet:
        persist: true
    - data/proc/quality.parquet:
        persist: true

  cls-political:
    cmd: python stages/make_cls_political.py
    deps:
    - stages/make_cls_political.py
    - data/proc/posts.parquet
    - data/proc/posts-text.parquet
    outs:
    - data/proc/cls-political.parquet:
        persist: true

  negativity-ground-truth:
    cmd: python stages/ml/make_negativity_ground_truth.py
    deps:
    - stages/ml/make_negativity_ground_truth.py
    - data/raw/negativity-ground-truth.json.gz
    outs:
    - data/proc/gpt/negativity-ground-truth.parquet:
        persist: true

  negativity-experiment-requests:
    cmd: python stages/ml/make_gpt_negativity_experiment_requests.py
    params:
    - gpt.negativity.experiment
    deps:
    - stages/ml/make_gpt_negativity_experiment_requests.py
    - data/proc/gpt/negativity-ground-truth.parquet
    outs:
    - data/proc/gpt/negativity-experiment-requests.jsonl.gz:
        persist: true

  negativity-experiment-jobs:
    cmd: python stages/ml/make_gpt_negativity_experiment_jobs.py
    params:
    - gpt.negativity.experiment
    deps:
    - stages/ml/make_gpt_negativity_experiment_jobs.py
    - data/proc/gpt/negativity-experiment-requests.jsonl.gz
    outs:
    - data/proc/gpt/negativity-experiment-jobs.jsonl.gz:
        persist: true

  negativity-experiment-responses:
    cmd: python stages/ml/make_gpt_negativity_experiment_responses.py
    deps:
    - stages/ml/make_gpt_negativity_experiment_responses.py
    - data/proc/gpt/negativity-experiment-jobs.jsonl.gz
    outs:
    - data/proc/gpt/negativity-experiment-responses.jsonl.gz:
        persist: true

  negativity-experiment-output:
    cmd: python stages/ml/make_gpt_negativity_experiment_output.py
    deps:
    - stages/ml/make_gpt_negativity_experiment_output.py
    - data/proc/gpt/negativity-experiment-responses.jsonl.gz
    outs:
    - data/proc/gpt/negativity-experiment.parquet:
        persist: true

  negativity-requests:
    cmd: python stages/ml/make_gpt_negativity_requests.py
    params:
    - gpt.negativity.batch
    deps:
    - stages/ml/make_gpt_negativity_requests.py
    - data/proc/dataset.parquet
    - data/proc/cls-political.parquet
    - data/proc/posts-text.parquet
    - ml/prompts/negativity/negativity.md
    outs:
    - data/proc/gpt/negativity-requests.jsonl.gz:
        persist: true

  negativity-jobs:
    cmd: python stages/ml/make_gpt_negativity_jobs.py
    params:
    - gpt.negativity.batch
    deps:
    - stages/ml/make_gpt_negativity_jobs.py
    - data/proc/gpt/negativity-requests.jsonl.gz
    outs:
    - data/proc/gpt/negativity-jobs.jsonl.gz:
        persist: true

  negativity-responses:
    cmd: python stages/ml/make_gpt_negativity_responses.py
    deps:
    - stages/ml/make_gpt_negativity_responses.py
    - data/proc/gpt/negativity-jobs.jsonl.gz
    outs:
    - data/proc/gpt/negativity-responses.jsonl.gz:
        persist: true

  negativity-output:
    cmd: python stages/ml/make_gpt_negativity_output.py
    deps:
    - stages/ml/make_gpt_negativity_output.py
    - data/proc/gpt/negativity-responses.jsonl.gz
    outs:
    - data/proc/gpt/negativity.parquet:
        persist: true

  negativity-dataset:
    cmd: python stages/ml/make_negativity_dataset.py
    params:
    - ml.dataset.negativity
    deps:
    - stages/ml/make_negativity_dataset.py
    - data/proc/gpt/negativity.parquet
    - data/proc/gpt/negativity-ground-truth.parquet
    - data/proc/gpt/negativity-requests.jsonl.gz
    outs:
    - ml/datasets/negativity:
        persist: true

  negativity-train:
    cmd: python stages/ml/negativity_hyper.py
    params:
    - ml.hyper.negativity
    - ml.models.negativity
    deps:
    - stages/ml/negativity_hyper.py
    - ml/datasets/negativity
    outs:
    - data/proc/negativity-hyper.parquet:
        persist: true

  glmm:
    foreach:
    - negativity
    - reactions
    - comments
    - shares
    do:
      cmd: Rscript stages/glmm_${item}.R
      deps:
      - stages/glmm_${item}.R
      - data/proc/dataset.parquet
      outs:
      - models/glmm/${item}:
          persist: true

  articles-sample:
    cmd: python stages/make_articles_sample.py
    deps:
    - stages/make_articles_sample.py
    - data/raw/articles-sample.xlsx
    outs:
    - data/proc/articles-sample.parquet:
        persist: true

  # predictions:
  #   cmd: Rscript stages/make_predictions.R
  #   deps:
  #   - stages/make_predictions.R
  #   - data/proc/dataset.parquet
  #   - models/glmm/reactions
  #   - models/glmm/comments
  #   - models/glmm/shares
  #   outs:
  #   - data/proc/predictions.parquet:
  #       persist: true

  # ml-datasets:
  #   foreach:
  #   - political
  #   - negativity
  #   do:
  #     cmd: python stages/ml/make_dataset_${item}.py
  #     deps:
  #     - stages/ml/make_dataset_${item}.py
  #     - data/ml/${item}
  #     params:
  #     - annotations.${item}
  #     outs:
  #     - ml/datasets/${item}:
  #         persist: true

  # train:
  #   foreach:
  #   - political
  #   - negativity
  #   do:
  #     cmd: python stages/train_${item}.py
  #     deps:
  #     - ml/datasets/${item}
  #     - stages/train_${item}.py
  #     outs:
  #     - ml/classifiers/${item}:
  #         persist: true

  # labels:
  #   foreach:
  #     - political
  #     - negativity
  #   do:
  #     cmd: python stages/make_labels.py --model='"${item}"'
  #     deps:
  #     - stages/make_labels.py
  #     - ml/classifiers/${item}
  #     - data/proc/posts-text.parquet
  #     outs:
  #     - data/proc/cls-${item}.parquet:
  #         persist: true

  # merge-labels:
  #   cmd: python stages/merge_labels.py
  #   deps:
  #   - stages/merge_labels.py
  #   - data/proc/cls-political.parquet
  #   - data/proc/cls-negativity.parquet
  #   outs:
  #   - data/proc/cls.parquet:
  #       persist: true
