paths:
  make!:            "newsuse.config:Paths"
  data:             "data"
  raw:              "@data/raw"
  proc:             "@data/proc"
  aux:              "@data/aux"
  posts:            "@proc/posts.parquet"
  text:             "@proc/posts-text.parquet"
  dataset:          "@proc/dataset.parquet"
  daily_counts:     "@proc/daily-counts.parquet"
  quality:          "@proc/data-quality.parquet"
  outlet_meta:      "@proc/outlet-meta.parquet"
  cls_political:    "@proc/cls-political.parquet"
  cls_valence:      "@proc/cls-valence.parquet"
  labels:           "@proc/cls.parquet"
  final:            "@proc/final.parquet"
  articles_sample:  "@proc/articles-sample.parquet"
  predictions:      "@proc/predictions.parquet"
  followers:        "@raw/followers.parquet"
  mldata:           "@data/ml"
  ml:               "ml"
  glmm:             "glmm"
  figures:          "figures"
  tables:           "tables"
  prompts:          "@ml/prompts"
  gpt:              "@proc/gpt/"
  annotations:      "annotations"
  valence_hyper:     "@proc/valence-hyper.parquet"
  analyses:          "analyses"

categorical:
  country:
    us:  United States
    uk:  United Kingdom
    irl: Ireland
    pl:  Poland
    fr:  France
    esp: Spain
  quality: ["low", "medium", "high"]
  ideology: ["left", "center", "right"]
  political: ["non-political", "political"]
  event: {-1: "negative", 0: "neutral", 1: "positive"}
  sentiment: {-1: "negative", 0: "neutral", 1: "positive"}
  valence: {-2: "very negative", -1: "negative", 0: "neutral", 1: "positive", 2: "very positive"}

engagement:
  - reactions
  - comments
  - shares

posts:
  start_date: "2020-01-01"
  end_date: "2024-04-01"

dataset:
  usecols:
  - key
  - country
  - name
  - timestamp
  - type
  - has_snippet
  - likes
  - reactions_LIKE
  - reactions_LOVE
  - reactions_WOW
  - reactions_HAHA
  - reactions_ANGRY
  - reactions_SAD
  - comments
  - shares
  - ini
  - post_url
  min_posts_per_day: 2

glmm:
  defaults: &glmm_defaults
    seed: 0
    noncentered: false
    fit: &glmm_fit
      draws: 2000
      tune: 2000
      chains: 4
      cores: 4
      target_accept: 0.95
      progress_bar: true
      inference_method: nutpie
      nuts_sampler_kwargs:
        backend: jax
    ppd:
      draws: 100
      sample_new_groups: true
      include_group_specific: true
      kind: response
    epred:
      samples_per_simple_effect: 100
      predict:
        include_group_specific: true
        sample_new_groups: true
        kind: response_params
  valence:
    default: &glmm_valence_default
      <<: *glmm_defaults
      sample: 1_000_000
      seed: 1
      formula: >
        {response} ~ 0
          + country * political
          + (1 + political | outlet)
          + (1 + political | country:year:month)
      family: cumulative
      noncentered: true
      common:
        - political
        - country
      group:
        - outlet
        - year
        - month
      fit:
        <<: *glmm_fit
    by:
      sample: 100_000
      target_accept: 0.9
      seed: 2
      formula: >
        {response} ~ 0
          + country * political * {by}
          + (1 + political * {by} | outlet)
          + (1 + political * {by} | country:year:month)
    targets:
      event:
        response: event
        <<: *glmm_valence_default
        seed: 543
      sentiment:
        response: sentiment
        <<: *glmm_valence_default
        seed: 17
      structural:
        response: sentiment
        <<: *glmm_valence_default
        sample: 1_000_000
        seed: 303
        formula: >
          {response} ~ 0
            + country * political * event
            + (1 + political * event | outlet)
        common:
          - event
          - political
          - country
        group:
          - outlet

  engagement:
    default: &glmm_engagement_default
      <<: *glmm_defaults
      sample: 500_000
      fit:
        <<: *glmm_fit
        target_accept: 0.8
        tune: 1000
        draws: 1000
      common:
        - political
        - country
      group:
        - outlet
        - weekend
        - year
        - month
      formula:
        - >
          {response} ~ 1
            + political * country * {valence}
            + (1 + political * {valence} | outlet)
        - >
          alpha ~ (1 | outlet)
      family: negativebinomial
    by:
      sample: 100_000
      target_accept: 0.9
      seed: 17
      formula:
        - >
          {response} ~ 1
            + political * country * {valence} * {by}
            + (1 + political * {valence} | outlet)
        - >
          alpha ~ (1 | outlet)
    targets:
      reactions:
        response: reactions
        <<: *glmm_engagement_default
      comments:
        response: comments
        <<: *glmm_engagement_default
      shares:
        response: shares
        <<: *glmm_engagement_default

classification:
  political:
    model:
      source: huggingface
      name: sztal/erc-newsuse-political

articles_sample:
  groupsize: 5

inference:
  alpha: 0.05
  conf: ${eval:1-${.alpha}}
  adjust: holm

xarray:
  display_style: text

arviz:
  data.load: eager
  stats.ci_prob: 0.95

plotting:
  style:  tableau-colorblind10
  usetex: true
  color:
    palette:
      gold:       "#ecc00f"
      red:        "#f10d71"
      green:      "#7adf06"
      blue:       "#5bbdff"
      brown:      "#ae6f4a"
      teal:       "#1cdae4"
      purple:     "#c618cc"
      white:      "white"
      gray:       "#bdbaba"
      black:      "black"
    semantics:
      other:      ${..palette.gray}
      overall:    ${..palette.black}
      political:  ${..palette.gold}
      negative:   ${..palette.black}
      positive:   ${..palette.blue}
      countries:
        us:        ${...palette.blue}
        uk:        ${...palette.red}
        irl:       ${...palette.green}
        pl:        ${...palette.gold}
        fr:        ${...palette.purple}
        esp:       ${...palette.brown}
      quality:
        low:      "#b6b6d8"
        medium:   "#8683bd"
        high:     "#61409b"
      ideology:
        left:     "#00AEF3"
        center:   ${...palette.gray}
        right:    "#D81F29"
    event:
      - ${..semantics.negative}
      - ${..semantics.other}
      - ${..semantics.positive}
    sentiment:
      - ${..semantics.negative}
      - ${..semantics.other}
      - ${..semantics.positive}
    valence: ["#000000", "#2b363a", "#576c73", "#82a3ad", "#add8e6"]
    quality:
      - ${..semantics.quality.low}
      - ${..semantics.quality.medium}
      - ${..semantics.quality.high}
    ideology:
      - ${..semantics.ideology.left}
      - ${..semantics.ideology.center}
      - ${..semantics.ideology.right}
    political:
      - ${..semantics.other}
      - ${..semantics.political}
    countries:
      - ${..semantics.countries.us}
      - ${..semantics.countries.uk}
      - ${..semantics.countries.irl}
      - ${..semantics.countries.pl}
      - ${..semantics.countries.fr}
      - ${..semantics.countries.esp}
  params:
    font.family:           sans-serif
    # font.sans-serif:       Montserrat
    text.usetex:           ${..usetex}
    text.latex.preamble:   \usepackage{amsmath,amsfonts,amssymb,sfmath,xcolor}
    figure.figsize:        [5, 5]
    figure.labelsize:      x-large
    figure.titlesize:      xx-large
    figure.titleweight:    bold
    figure.dpi:            300
    savefig.bbox:          tight
    axes.grid:             false
    axes.axisbelow:        true
    axes.titleweight:      bold
    axes.titlesize:        large
    axes.labelsize:        large
    scatter.marker:        o
    scatter.edgecolors:    black
    lines.markeredgecolor: black
    lines.markeredgewidth: 1
  objects:
    dot:
      pointsize: 8
      edgecolor: black
      edgewidth: 1
      artist_kws:
        zorder: 10
    range:
      color: black
      linewidth: 2
    line:
      linestyle: dashed
      linewidth: 2
