paths:
  make!:            "newsuse.config:Paths"
  data:             "data"
  raw:              "@data/raw"
  proc:             "@data/proc"
  aux:              "@data/aux"
  posts:            "@proc/posts.parquet"
  text:             "@proc/posts-text.parquet"
  dataset:          "@proc/dataset.parquet"
  daily_counts:     "@proc/daily-counts.parquet"
  quality:          "@proc/data-quality.parquet"
  outlet_meta:      "@proc/outlet-meta.parquet"
  cls_political:    "@proc/cls-political.parquet"
  cls_valence:      "@proc/cls-valence.parquet"
  labels:           "@proc/cls.parquet"
  final:            "@proc/final.parquet"
  articles_sample:  "@proc/articles-sample.parquet"
  predictions:      "@proc/predictions.parquet"
  followers:        "@raw/followers.parquet"
  mldata:           "@data/ml"
  ml:               "ml"
  glmm:             "glmm"
  figures:          "figures"
  prompts:          "@ml/prompts"
  gpt:              "@proc/gpt/"
  annotations:      "annotations"
  valence_hyper:     "@proc/valence-hyper.parquet"
  analyses:          "analyses"

categorical:
  country:
    us:  United States
    uk:  United Kingdom
    irl: Ireland
    pl:  Poland
    fr:  France
    esp: Spain
  quality: ["low", "medium", "high"]
  ideology: ["left", "center", "right"]
  political: ["non-political", "political"]
  event: [-1, 0, 1]
  sentiment: [-1, 0, 1]
  valence: [-2, -1, 0, 1, 2]

engagement:
  - reactions
  - comments
  - shares

posts:
  start_date: "2020-01-01"
  end_date: "2024-04-01"

dataset:
  usecols:
  - key
  - country
  - name
  - timestamp
  - type
  - has_snippet
  - likes
  - reactions_LIKE
  - reactions_LOVE
  - reactions_WOW
  - reactions_HAHA
  - reactions_ANGRY
  - reactions_SAD
  - comments
  - shares
  - ini
  - post_url
  min_posts_per_day: 2

glmm:
  defaults: &glmm_defaults
    seed: 0
    fit: &glmm_fit
      draws: 2000
      tune: 2000
      chains: 4
      cores: 4
      target_accept: 0.99
      progress_bar: true
      inference_method: nutpie
      nuts_sampler_kwargs:
        backend: jax
    ppd: &glmm_ppd
      draws: 100
      sample_new_groups: true
      include_group_specific: true
      kind: response
    epred: &glmm_epred
      samples_per_simple_effect: 100
      predict: &glmm_epred_predict
        include_group_specific: true
        sample_new_groups: true
        kind: response_params
  valence:
    default: &glmm_valence_default
      <<: *glmm_defaults
      sample: 1_000_000
      seed: 1
      formula: >
        {response} ~ 0
          + political * country
          + (1 + political | outlet)
          + (1 + political | country:year:month)
      family: cumulative
      noncentered: true
      common:
        - political
        - country
      group:
        - outlet
        - year
        - month
      fit:
        <<: *glmm_fit
    targets:
      event:
        response: event
        <<: *glmm_valence_default
        seed: 543
      sentiment:
        response: sentiment
        <<: *glmm_valence_default
        seed: 17
      structural:
        response: sentiment
        <<: *glmm_valence_default
        sample: 500_000
        seed: 303
        formula: >
          {response} ~ 0
            + event * political * country
            + (1 + political | outlet)
        common:
          - event
          - political
          - country
        group:
          - outlet
  engagement:
    default: &glmm_engagement_default
      <<: *glmm_defaults
      sample: 250_000
      common:
        - political
        - country
        - event
        - sentiment
      group:
        - outlet
        - weekend
        - year
        - month
      formula:
        - >
          {response} ~ 1
            + event * sentiment
            + political * event * country + political * sentiment * country
            + (1 | outlet) + (1 | country:year:month)
        - >
          alpha ~ country + (1 | outlet)
      model:
      family: negativebinomial
    targets:
      reactions:
        response: reactions
      comments:
        response: comments
      shares:
        response: shares

classification:
  political:
    model:
      source: huggingface
      name: sztal/erc-newsuse-political

articles_sample:
  groupsize: 10

gpt:
  header: &gpt_default_header
    method: POST
    url: /v1/responses
  batch_size: &gpt_default_batch_size 2500
  valence:
    experiment:
      params:
        gpt-5:
          model:
            - gpt-5
            - gpt-5-mini
            - gpt-5-nano
          reasoning:
            - effort: minimal
            - effort: low
            - effort: medium
            - effort: high
          text:
            - verbosity: low
        gpt-4.1:
          model:
            - gpt-4.1
            - gpt-4.1-mini
            - gpt-4.1-nano
          temperature:
            - 0.0
      prompts:
        - valence.md
        - event.md
        - sentiment.md
      header:
        <<: *gpt_default_header
      batch_size: *gpt_default_batch_size
    batch:
      params: &gpt_batch_params
        model: gpt-5
        reasoning:
          effort: medium
        text:
          verbosity: medium
      header:
          <<: *gpt_default_header
      batch_size: *gpt_default_batch_size
      sample:
        size_per_group: 2000
        min_words: 5
        countries: []
        political:
          - OTHER
          - POLITICAL
        seed: 535017
      targets:
        event:
          <<: *gpt_batch_params
        sentiment:
          <<: *gpt_batch_params

inference:
  alpha: 0.05
  conf: ${eval:1-${.alpha}}
  adjust: holm

ml:
  dataset:
    defaults: &ml_dataset_defaults
      training: 0.8
      testing: 0.1
      validation: 0.1
    valence:
      <<: *ml_dataset_defaults
      seed: 34280
  inference:
    batch_size: ${eval:${oc.env:NEWSUSE_ML_INFERENCE_BATCH_SIZE,32}}
  tokenize: &ml_tokenize_defaults
    padding: max_length
    truncation: true
  training: &ml_training_defaults
    callbacks:
      - make!: transformers:EarlyStoppingCallback
        early_stopping_patience: 2
    arguments: &ml_training_arguments_defaults
      make!: transformers:TrainingArguments
      num_train_epochs: ${eval:${oc.env:NEWSUSE_NUM_TRAIN_EPOCHS,10}}
      per_device_eval_batch_size: ${eval:${oc.env:NEWSUSE_PER_DEVICE_EVAL_BATCH_SIZE,32}}
      per_device_train_batch_size: ${eval:${oc.env:NEWSUSE_PER_DEVICE_TRAIN_BATCH_SIZE,16}}
      learning_rate: 1e-6
      seed: 303
      gradient_checkpointing: ${eval:${oc.env:NEWSUSE_GRADIENT_CHECKPOINTING,1}}
      fp16: ${eval:${oc.env:NEWSUSE_FP16,1}}
      metric_for_best_model: loss
      save_strategy: epoch
      eval_strategy: epoch
      eval_on_start: true
      logging_strategy: epoch
      load_best_model_at_end: true
      overwrite_output_dir: true
  hyper:
    defaults: &ml_hyper_defaults
      study: &ml_hyper_study_defaults
        direction: maximize
        load_if_exists: ${eval:${oc.env:NEWSUSE_OPTUNA_RESUME,1}}
      optimize:
        n_jobs: ${eval:${oc.env:NEWSUSE_OPTUNA_N_JOBS,1}}
        n_trials: ${eval:${oc.env:NEWSUSE_OPTUNA_N_TRIALS,50}}
        show_progress_bar: true
      space:
        newsuse:
          base:
            type: categorical
            choices:
            # - distilbert
            - xlm-large
          ordinal_logit_bias_scale:
            type: float
            low: 1.0
            high: 8.0
            step: 0.5
          num_shared_layers:
            type: int
            low: 0
            high: 0
          num_head_layers:
            type: int
            low: 0
            high: 4
          head_poolers:
            type: categorical
            choices:
            - true
            - false
          dropout:
            type: float
            low: 0.0
            high: 0.3
            step: 0.05
        args:
          learning_rate:
            type: float
            low: 1e-7
            high: 1e-4
            log: true
          warmup_ratio:
            type: float
            low: 0
            high: 0.5
            step: ${eval:1 / ${ml.training.arguments.num_train_epochs}}
          weight_decay:
            type: float
            low: 0
            high: 0.01
            step: 0.002
          lr_scheduler_type:
            type: categorical
            choices:
            - linear
            - cosine
            - cosine_with_restarts
          seed:
            type: categorical
            choices:
            - 923416180
            - 947936097
            - 913180696
            - 107285332
            - 325748676
            - 1364790667
            - 2894555970
            - 365673098
            - 415169889
            - 3396084250
    valence:
      <<: *ml_hyper_defaults
      study:
        study_name: valence
        <<: *ml_hyper_study_defaults
  models:
    valence:
      defaults: &ml_model_valence_defaults
        base: {}
        newsuse: {}
        tokenize:
          <<: *ml_tokenize_defaults
        training:
          <<: *ml_training_defaults
          arguments:
            <<: *ml_training_arguments_defaults
      distilbert:
        checkpoint: distilbert-base-multilingual-cased
        <<: *ml_model_valence_defaults
      xlm-large:
        checkpoint: xlm-roberta-large
        <<: *ml_model_valence_defaults

xarray:
  display_style: text

arviz:
  data.load: eager
  stats.ci_prob: 0.95

plotting:
  style:  tableau-colorblind10
  usetex: true
  color:
    palette:
      gold:       "#ecc00f"
      red:        "#f10d71"
      green:      "#7adf06"
      blue:       "#5bbdff"
      brown:      "#ae6f4a"
      teal:       "#1cdae4"
      purple:     "#c618cc"
      white:      "white"
      gray:       "#bdbaba"
      black:      "black"
    semantics:
      other:      ${..palette.gray}
      overall:    ${..palette.black}
      political:  ${..palette.gold}
      negative:   ${..palette.black}
      positive:   ${..palette.blue}
      countries:
        us:        ${...palette.blue}
        uk:        ${...palette.red}
        irl:       ${...palette.green}
        pl:        ${...palette.gold}
        fr:        ${...palette.purple}
        esp:       ${...palette.brown}
      quality:
        low:      "#b6b6d8"
        medium:   "#8683bd"
        high:     "#61409b"
      ideology:
        left:     "#00AEF3"
        center:   ${...palette.gray}
        right:    "#D81F29"
    event:
      - ${..semantics.negative}
      - ${..semantics.other}
      - ${..semantics.positive}
    sentiment:
      - ${..semantics.negative}
      - ${..semantics.other}
      - ${..semantics.positive}
    valence: ["#000000", "#2b363a", "#576c73", "#82a3ad", "#add8e6"]
    quality:
      - ${..semantics.quality.low}
      - ${..semantics.quality.medium}
      - ${..semantics.quality.high}
    ideology:
      - ${..semantics.ideology.left}
      - ${..semantics.ideology.center}
      - ${..semantics.ideology.right}
    political:
      - ${..semantics.other}
      - ${..semantics.political}
    countries:
      - ${..semantics.countries.us}
      - ${..semantics.countries.uk}
      - ${..semantics.countries.irl}
      - ${..semantics.countries.pl}
      - ${..semantics.countries.fr}
      - ${..semantics.countries.esp}
  params:
    font.family:           sans-serif
    # font.sans-serif:       Montserrat
    text.usetex:           ${..usetex}
    text.latex.preamble:   \usepackage{amsmath,amsfonts,amssymb,sfmath,xcolor}
    figure.figsize:        [5, 5]
    figure.labelsize:      x-large
    figure.titlesize:      xx-large
    figure.titleweight:    bold
    figure.dpi:            300
    savefig.bbox:          tight
    axes.grid:             false
    axes.axisbelow:        true
    axes.titleweight:      bold
    axes.titlesize:        large
    axes.labelsize:        large
    scatter.marker:        o
    scatter.edgecolors:    black
    lines.markeredgecolor: black
    lines.markeredgewidth: 1
  objects:
    dot:
      pointsize: 10
      edgecolor: black
      edgewidth: 1
      artist_kws:
        zorder: 10
    range:
      color: black
      linewidth: 2
    line:
      linestyle: dashed
      linewidth: 2
