---
title: "Engagement model"
subtitle: "Count regression with fixed and random effects"
author: "Szymon Talaga"
date: last-modified
date-format: "MMMM D, YYYY | HH:mm:ss (Z)"
toc: true
toc-depth: 3
toc-location: left
execute:
  echo: false
  warning: false
  cache: false
  daemon: false
format:
  html:
    grid:
      margin-width: 350px
    embed-resources: true
  pdf:
    toc: false
    number-sections: true
    colorlinks: true
reference-location: margin
citation-location: margin
---

```{r}
library(arrow)
library(stringr)
library(dplyr)
library(purrr)
library(tibble)
library(emmeans)
library(broom)
library(broom.mixed)
library(reticulate)
library(lubridate)
library(glmmTMB)

use_condaenv("polneg-repro")

project <- import("project")
config  <- project$config
paths   <- project$paths[["__copy__"]]()

alpha     <- config$inference$alpha
conf      <- config$inference$conf
adjust    <- config$inference$adjust
countries <- config$countries$order
countries <- countries[0L:length(countries)]

emm_options(
    emmeans  = list(type = "response", level = conf, adjust = adjust),
    contrast = list(adjust = adjust),
    summary  = list(infer = TRUE)
)
```

```{python}
import importlib
from typing import Mapping
import datetime
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib as mpl
import matplotlib.lines
import matplotlib.dates
import matplotlib.pyplot as plt
from matplotlib.patheffects import withStroke
import seaborn as sns
import seaborn.objects as so
from project import config, paths

mpl.style.use(config.plotting.style)
mpl.rcParams.update({
    k: v.make() if isinstance(v, Mapping) and "make!" in v else v
    for k, v in config.plotting.params.items()
})

figpath = paths.figures / "glmm"
figpath.mkdir(parents=True, exist_ok=True)

countries = dict(config.countries.labels)
colors    = {"overall": "black", **config.plotting.color.semantics}
```

```{r}
data <- as.character(paths$dataset) %>%
    read_parquet %>%
    tibble %>%
    mutate(across(c(year, month, day), as.factor)) %>%
    mutate(
        political  = relevel(as.factor(political), "OTHER"),
        negativity = relevel(as.factor(negativity), "OTHER"),
        country    = factor(country, levels = countries),
    )
```

```{r}
glmm_r <- readRDS(as.character(paths$glmm / "reactions" / "0.rds"))
glmm_c <- readRDS(as.character(paths$glmm / "comments" / "0.rds"))
glmm_s <- readRDS(as.character(paths$glmm / "shares" / "0.rds"))
gc()
```

# Reference grids for the models

```{r}
rgr <- ref_grid(glmm_r)
rgc <- ref_grid(glmm_c)
rgs <- ref_grid(glmm_s)
gc()
```

# Estimated marginal means

```{r}
countries <- rgr@levels$country
polvals   <- str_to_lower(rgr@levels$political)
negvals   <- str_to_lower(rgr@levels$negativity)

emmr  <- emmeans(rgr, ~country*political*negativity)
emmc  <- emmeans(rgc, ~country*political*negativity)
emms  <- emmeans(rgs, ~country*political*negativity)

emmra <- emmeans(rgr, ~political*negativity)
emmca <- emmeans(rgc, ~political*negativity)
emmsa <- emmeans(rgs, ~political*negativity)
```

## Negative/other contrasts

```{r}
by    <- c("country", "political")
coefc <- coef(contrast(emmr, by = by, method = "trt.vs.ctrl"))
coefo <- emmr %>%
    contrast(by = "country", interaction = "trt.vs.ctrl") %>%
    coef %>%
    mutate(across(starts_with("c."),~{
        abs(.x) * if_else(negativity == "OTHER", -1, 1) / length(polvals)
    }))

.countries <- c("overall", countries)

Co <- select(coefo, starts_with("c.")) %>%
    mutate(o = rowMeans(.), .before = 1L) %>%
    set_names(str_c("overall", .countries, sep = ":"))
Cc <- coefc %>%
    mutate(
        `o.1` = rowSums(pick(starts_with("c."))) * (political == "OTHER"),
        `o.2` = rowSums(pick(starts_with("c."))) * (political != "OTHER"),
        .before = c.1
    ) %>%
    mutate(across(c(o.1, o.2), ~.x / length(countries))) %>%
    select(starts_with("o."), starts_with("c.")) %>%
    set_names(c(
        str_c(polvals, "overall", sep = ":"),
        str_c(
            rep(polvals, each = length(countries)),
            rep(countries, length(polvals)),
            sep = ":"
        )
    ))

C <- select(
    cbind(Co, Cc),
    starts_with("overall:"),
    starts_with("other:"),
    starts_with("political:")
)

conr <- contrast(emmr, method = C)
conc <- contrast(emmc, method = C)
cons <- contrast(emms, method = C)

.tidy <- function(con) mutate(
    as_tibble(con),
    country   = str_split_i(contrast, ":", 2L),
    political = str_split_i(contrast, ":", 1L),
    .after = 1L
)

eff_r <- .tidy(conr)
eff_c <- .tidy(conc)
eff_s <- .tidy(cons)
```

# Figure

```{python}
palette   = [colors["other"], colors["overall"], colors["political"]]
gap       = 0.05
ymin      = "asymp.LCL"
ymax      = "asymp.UCL"
hue       = "political"
hue_ord   = ["non-political", "overall", "political"]
text      = "annot"
marker    = "sig"
pointsize = "sig"
nlabels   = {"OTHER": "other", "NEGATIVE": "negative"}
plabels   = {"OTHER": "non-political", "POLITICAL": "political"}
boxprops  = {"facecolor": "white"}
dodgekw   = {"empty": "drop"}
rangekw   = {"color": "black", "linewidth": 3}
linekw    = {"linewidth": 2, "linestyle": "-"}
dotkw     = {
    "pointsize": 10,
    "edgecolor": "black",
    "artist_kws": {"zorder": 10}
}
textkw    = {
    "color":      "black",
    "fontsize":   8,
    "halign":     "center",
    "artist_kws": {"zorder": 90},
}
starkw    = {
    "edgecolor":  "black",
    "marker":     "*",
    "color":      colors["negative"],
    "artist_kws": {"zorder": 20}
}
```

```{python}
from itertools import product

metrics   = ["reactions", "comments", "shares"]
fig, axes = plt.subplots(
    nrows=len(metrics),
    figsize=(7, 9),
    sharey=True
)
x, y = "country", "ratio"
keys = list(product(["overall", *countries], hue_ord))

for ax, metric in zip(axes.flat, metrics, strict=True):
    key = metric[0]
    con = (
        getattr(r, f"eff_{key}")
        .replace({"political": {"other": "non-political"}})
        .set_index([x, "political"])
        .loc[keys]
        .reset_index()
    )
    con[x] = con[x].map(lambda x: countries.get(x, r"\textbf{Overall}"))
    # con[[y, ymin, ymax]] -= 1
    con["sig"] = con["p.value"] <= r.alpha
    (
        so.Plot(con, x=x, y=y, color=hue)
        .add(so.Dot(**dotkw), so.Dodge())
        .add(
            so.Range(**rangekw), so.Dodge(),
            ymin=ymin, ymax=ymax
        )
        .add(
            so.Dot(
                color=colors["negative"], marker="*", edgecolor="k",
                artist_kws={"zorder": 90}
            ),
            so.Dodge(),
            pointsize="sig"
        )
        .scale(color=palette, pointsize=[0, 15])
        .on(ax)
        .show()
    )
    ax.axvline(.5, ls="--", color="k")
    ax.axhline(1.0, ls=":", color="k")
    ax.set_title(metric.title())
    ax.set_xlabel(None)
    ax.set_ylabel(None)
    ax.tick_params(bottom=False, labelbottom=False)

axes.flatten()[0].tick_params(top=True, labeltop=True)
axes.flatten()[-1].tick_params(bottom=True, labelbottom=True)

fig.legends.clear()
fig.supylabel(r"Ratio of estimated marginal means (negative/non-negative)")
fig.tight_layout()
fig.savefig(figpath / "engagement.pdf")
```


# Tables
## Estimates

```{python}
cilo = rf"{r.alpha/2*100:.1f}\%"
cihi = rf"{(1-r.alpha/2)*100:.1f}\%"

(
    pd.concat({
        m.title(): (
            getattr(r, f"eff_{m[0]}")
            .pipe(lambda df: pd.DataFrame({
                "country": df["country"],
                "political": df["political"],
                "MR": df["ratio"],
                cilo: df["asymp.LCL"],
                cihi: df["asymp.UCL"],
            }))
            .set_index(["political"])
            .loc[["political", "other", "overall"]]
            .reset_index()
            .set_index(["country", "political"])
            .loc[[*countries, "overall"]]
            .rename({"other": "non-political"}, level="political")
            .rename(lambda x: countries.get(x, r"\textbf{Overall}"), level="country")
        )
        for m in ("reactions", "comments", "shares")
    }, axis=1)
    .pipe(lambda df: print(
        df.style
        .format(
            escape=False,
            precision=3,
            na_rep="",
        )
        .to_latex(
            multicol_align="c",
            multirow_align="t",
            hrules=True,
        )
    ))
)
```
